language: android
jdk:
    - oraclejdk8

android:
    components:
        # "tools" goes first, allowing fetching the latest version
        # of the android-sdk as well as the android API
        - tools
        - android-24
        - build-tools-24.0.2
        - platform-tools
        - extra-android-m2repository

env:
    - BUILDDIR=src/android

before_cache:
    - rm -f $BUILDDIR/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $BUILDDIR/.gradle/caches/
        - $BUILDDIR/.gradle/wrapper/

script:
    - cd $BUILDDIR
    - ./gradlew assembleDebug
